version: '3.8'

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
